feat: install by pasting fn

diff --git a/example b/example
--- a/example
+++ b/example
@@ -1,6 +1,31 @@
-#!/bin/sh                                        
+#!/bin/sh
 set -e
 
-# assuming you saved the realpath-compat file next to this script
-my_real_path="$(./realpath-compat "$0")" 
+realpath_compat() {
+  # if no arguments, print usage
+  if [ $# -eq 0 ]; then
+    echo "Usage: realpath_compat FILE [FILE ...]"
+    return 1
+  fi
+
+  # repeat for each argument
+  while [ $# -gt 0 ]; do
+    file="$1"
+    shift
+
+    if [ ! -e "$file" ]; then
+      echo "realpath_compat: $file: No such file or directory"
+      return 1
+    fi
+
+    realpath "$file" 2>/dev/null ||
+      readlink -f "$file" 2>/dev/null ||
+      zsh -c 'echo ${0:A}' "$file" 2>/dev/null ||
+      python3 -c "import os; import sys; print(os.path.realpath(sys.argv[1]))" "$file" 2>/dev/null ||
+      node -e "console.log(require('fs').realpathSync(process.argv[1]))" "$file" 2>/dev/null ||
+      echo "realpath_compat: $file: Could not resolve real path" >&2
+  done
+}
+
+my_real_path="$(realpath_compat "$0")"
 echo "This script's real path is: ${my_real_path}, and that's true even if you call it via a symlink."
diff --git a/realpath-compat b/realpath-compat
--- a/realpath-compat
+++ b/realpath-compat
@@ -3,14 +3,30 @@
 
 set -e
 
-if ! [ -e "$1" ]; then
-  echo "$0: could not find \"$1\"" >&2
-  exit 1
-fi
+realpath_compat() {
+  # if no arguments, print usage
+  if [ $# -eq 0 ]; then
+    echo "Usage: realpath_compat FILE"
+    return 1
+  fi
 
-realpath "$1" 2>/dev/null \
-|| readlink -f "$1" 2>/dev/null \
-|| zsh -c 'echo ${0:A}' "$1" 2>/dev/null \
-|| python3 -c "import os; import sys; print(os.path.realpath(sys.argv[1]))" "$1" 2>/dev/null \
-|| node -e "console.log(require('fs').realpathSync(process.argv[1]))" "$1" 2>/dev/null \
-|| echo "$0: could not find real path for \"$1\"" >&2
+  # repeat for each argument
+  while [ $# -gt 0 ]; do
+    file="$1"
+    shift
+
+    if [ ! -e "$file" ]; then
+      echo "realpath_compat: $file: No such file or directory"
+      return 1
+    fi
+
+    realpath "$file" 2>/dev/null ||
+      readlink -f "$file" 2>/dev/null ||
+      zsh -c 'echo ${0:A}' "$file" 2>/dev/null ||
+      python3 -c "import os; import sys; print(os.path.realpath(sys.argv[1]))" "$file" 2>/dev/null ||
+      node -e "console.log(require('fs').realpathSync(process.argv[1]))" "$file" 2>/dev/null ||
+      echo "$0: could not find real path for \"$file\"" >&2
+  done
+}
+
+realpath_compat "$@"
